# Use official Python image
FROM python:3.13-rc-slim

# Set working directory
WORKDIR /app

# Install uv globally
RUN pip install uv

# Copy project files
COPY . .

# Remove any host virtual environment that might’ve been copied
RUN rm -rf .venv

# Install dependencies globally from pyproject.toml
RUN uv pip install --system .

# Expose Flask app port
EXPOSE 8002

# Run the app using uv
CMD ["uv", "run", "app.py"]
